#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "jenkins"
name = "Jenkins"
description.en = "Extendable continuous integration server"
description.fr = "Serveur d'intégration continue extensible"

version = "2.578~ynh1"

maintainers = [ ]

[upstream]
license = "MIT"
website = "https://jenkins.io"
userdoc = "https://www.jenkins.io/doc/book/"
code = "https://github.com/jenkinsci/jenkins"
cpe = "cpe:2.3:a:cloudbees:jenkins"

fund = "https://www.jenkins.io/donate"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = false

ldap = true
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/jenkins"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/jenkinsci/jenkins/releases/download/jenkins-2.578/jenkins_2.578_all.deb"
    sha256 = "146c4e92ac721611189ade654429e3689f71289caf1a58dd0ce8468369c2d393"
    format = "whatever"
    extract = false
    rename = "jenkins.deb"
    autoupdate.strategy = "latest_github_release"
    autoupdate.asset = "^jenkins_(.*)_all.deb$"
    autoupdate.version_regex = "^jenkins-(.*)$"
    autoupdate.needs_manual_tweaks = true

    [resources.sources.jenkins-plugin-manager]
    url = "https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/2.15.0/jenkins-plugin-manager-2.15.0.jar"
    sha256 = "a86853ec2e2933f37a4b471ba65099b61e03c87a80c2ef8fe2315eb135672d43"
    format = "whatever"
    extract = false
    rename = "jenkins-plugin-manager.jar"
    autoupdate.strategy = "latest_github_release"
    autoupdate.upstream = "https://github.com/jenkinsci/plugin-installation-manager-tool"
    autoupdate.asset = "^jenkins-plugin-manager-(.*).jar$"

    [resources.sources.jre]
    amd64.url = "https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.12%2B8/OpenJDK21U-jre_x64_linux_hotspot_21.0.12_8.tar.gz"
    amd64.sha256 = "8a379a67c91a3ae61ffb33d46e0a40c7ba35e70713c4db31cfca30492f792eff"
    arm64.url = "https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.12%2B8/OpenJDK21U-jre_aarch64_linux_hotspot_21.0.12_8.tar.gz"
    arm64.sha256 = "5f9c96b656827b9d14ebeda7739e25be554fa6d25669b03847c1df6e869c0679"
    autoupdate.strategy = "latest_github_release"
    autoupdate.version_regex = "jdk-(\\d+\\.\\d+\\.\\d+)\\+(.*)"
    autoupdate.upstream = "https://github.com/adoptium/temurin21-binaries"
    autoupdate.asset.amd64 = "OpenJDK.*-jre_x64_linux_hotspot_.*\\.tar\\.gz$"
    autoupdate.asset.arm64 = "OpenJDK.*-jre_aarch64_linux_hotspot_.*\\.tar\\.gz$"


    [resources.system_user]
    home = "/var/lib/jenkins"

    [resources.install_dir]
    dir = "/var/lib/jenkins"

    [resources.permissions]
    main.url = "/"
    github_webhook.url = "/github-webhook"
    github_webhook.allowed = "visitors"
    github_webhook.protected = false
    github_webhook.show_tile = false

    [resources.ports]
    main.default = 8095

    [resources.apt]
    packages = [
        "daemon",
        "net-tools"
    ]
