#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    test_upgrade_from.564fd0bbfcc25b6c7bc34af900d4d6e41fe5c630.name = "2.426.3~ynh2"
