#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    # test_upgrade_from.564fd0bbfcc25b6c7bc34af900d4d6e41fe5c630.name = "2.426.3~ynh2"
    test_upgrade_from.6baec716d6667d772bb5ff9862d466f8a63be453.name = "2.479.2~ynh1"
