#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    test_upgrade_from.1bac2a594e271d0af9fa0bf3dd7e962d1448060d.name = "2.550~ynh1"
