#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_clean_setup () {
	ynh_clean_check_starting
}
ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression --message="Load settings" --weight=3

app=$YNH_APP_INSTANCE_NAME

final_path=$(ynh_app_setting_get $app final_path)
domain=$(ynh_app_setting_get $app domain)

#=================================================
# STANDARD BACKUP STEPS
#=================================================
# BACKUP THE APP MAIN DIR
#=================================================
ynh_script_progression --message="Backup the app main dir" --weight=15

ynh_systemd_action --action=stop --service_name=jenkins
sleep 1

CHECK_SIZE "$final_path"
ynh_backup "$final_path"

#=================================================
# BACKUP THE NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Backup nginx configuration"

ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# SPECIFIC BACKUP
#=================================================
# BACKUP THE JENKINS' BOOT CONFIG
#=================================================

ynh_backup /etc/default/$app

#=================================================
# CHECK JENKINS STARTING
#=================================================
ynh_script_progression --message="Restart Jenkins" --weight=20

# Wait for Jenkins to be fully started
ynh_systemd_action --line_match="Jenkins is fully up and running" --log_path="/var/log/$app/$app.log" --timeout="300"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Backup completed" --last
