#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

#=================================================
# INSTALL JENKINS
#=================================================
ynh_script_progression "Installing Jenkins..."

# Download jenkins deb file and install it.
ynh_setup_source --dest_dir="$install_dir"
dpkg --install --force-confnew "$install_dir/jenkins.deb" || true
ynh_safe_rm "$install_dir/jenkins.deb"

#=================================================
# SETUP APPLICATION
#=================================================
ynh_script_progression "Setting up $app's service..."

ynh_replace --file="/lib/systemd/system/jenkins.service" \
    --match="Environment=\"JENKINS_PORT=8080\"" \
    --replace="Environment=\"JENKINS_PORT=$port\"\nEnvironment=\"JENKINS_PREFIX=$path\""

systemctl daemon-reload --quiet

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

yunohost service add "$app" --description="Jenkins Continuous Integration Server"

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service="$app" --action="restart" --wait_until="Jenkins is fully up and running" --log_path="systemd"

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
